[package]
name = "adventofcode-2025"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.2"
clap = { version = "4.4.10", features = ["derive"] }
itertools = "0.14.0"
